image: /baylibre/amlogic/meta-meson-runner:xenial-20190720-02Aug2019

build-initrd:
  tags: [ 'yocto' ]
  # Create and initialize the build environment
  # -------------------------------------------
    - rm -rf /tmp/build_env
    - git clone git://github.com/openembedded/openembedded-core --branch=thud --depth=1 /tmp/build_env
    - git clone git://github.com/openembedded/bitbake --branch=1.40 --depth=1 /tmp/build_env/bitbake
    - git clone $(pwd) /tmp/build_env/$(basename $(pwd))

  script:
    - bash scripts/build.sh /tmp/build_env amlogic-image-headless-initrd