variables:
  IMAGE_TAG: "2019-09-17-1"

services:
  - docker:dind

image: docker:latest

stages:
  - docker
  - initrd
  
before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build-docker:
  stage: docker
  script:
    # fetches the latest image (not failing if image is not found)
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    # builds the project, passing proxy variables, and vcs vars for LABEL
    # notice the cache-from, which is going to use the image we just pulled locally
    # the built image is tagged locally with the commit SHA, and then pushed to 
    # the GitLab registry
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:IMAGE_TAG
      scripts/Dockerfile
    - docker push $CI_REGISTRY_IMAGE:IMAGE_TAG

build-initrd:
  tags: [ 'yocto' ]
  stage: initrd
  image: $CI_REGISTRY_IMAGE:IMAGE_TAG
  
  before_script:
  # Create and initialize the build environment
  # -------------------------------------------
    - rm -rf /tmp/build_env
    - git clone git://github.com/openembedded/openembedded-core --branch=thud --depth=1 /tmp/build_env
    - git clone git://github.com/openembedded/bitbake --branch=1.40 --depth=1 /tmp/build_env/bitbake
    - git clone $(pwd) /tmp/build_env/$(basename $(pwd))

  script:
    - bash scripts/build.sh /tmp/build_env amlogic-image-headless-initrd