variables:
  IMAGE_TAG: "2019-09-17-2"

services:
  - docker:dind

image: docker:latest

stages:
  - docker
  - initrd
  
before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build-docker:
  stage: docker
  script:
    - docker pull $CI_REGISTRY_IMAGE:$IMAGE_TAG && exit 0 || true
    - >
      docker build
      --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG
      scripts/
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

build-initrd:
  tags: [ 'yocto' ]
  stage: initrd
  image: $CI_REGISTRY_IMAGE:$IMAGE_TAG
  
  before_script:
    - mkdir -p results
    - rm -rf /tmp/build_env
    - git clone git://github.com/openembedded/openembedded-core --branch=thud --depth=1 /tmp/build_env
    - git clone git://github.com/openembedded/bitbake --branch=1.40 --depth=1 /tmp/build_env/bitbake
    - git clone $(pwd) /tmp/build_env/$(basename $(pwd))

  script:
    - bash scripts/build.sh /tmp/build_env libretech-cc amlogic-image-headless-initrd
    - cp -ar /tmp/build_env/builld/tmp*/deploy/images/* $CI_PROJECT_DIR/results/

  artifacts:
    when: always
    paths:
      - results/